# Generated by Django 4.2.5 on 2023-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_list', '0004_problem_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('In progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
