# Generated by Django 4.2.5 on 2023-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_list', '0006_problem_assigned_user_problem_resolved_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('In progress', 'In progress'), ('resolved', 'Resolved'), ('confirmed', 'Confirmed')], default='new', max_length=20),
        ),
    ]
